### 
 
 GET  http://localhost:3003/api/blog

###  
  get http://localhost:3003/api/user




### post

post  http://localhost:3003/api/blog
       Content-Type: application/json
       Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcmJkdWxtdWppYiIsImlkIjoiNjEyY2M0M2FjMjliN2Y0MzMyMmVkNGIzIiwiaWF0IjoxNjMwMzU1MDY4fQ.y5opj8MB5URuQImHiOQ6RyzqSR0iB-MhztJjwLZ21cU

       {
          "author":"mj007",
          "url":"htttp://mujib.com"

        }
###
post  http://localhost:3003/api/user
  Content-Type: application/json

  {
    "username":"harbdulmujib",
    "password":"abdulife",
    "name":"mj007"
  }


###
  post  http://localhost:3003/api/login
      Content-Type: application/json

      {
        "username":"harbdulmujib",
        "password":"asiyanb"
      }



###
  delete http://localhost:3003/api/user/612cbeeb332cdd3c015062f

### 
 delete http://localhost:3003/api/blog/612cf129bdcfd89082247c35
 Content-Type: application/json
 Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcmJkdWxtdWppYiIsImlkIjoiNjEyY2M0M2FjMjliN2Y0MzMyMmVkNGIzIiwiaWF0IjoxNjMwNDA3MjI1fQ.SBhXdMD3bze418HmN6ndgEDI4J1YBIY5Xjyzdoo1wzI





